### ISSUE TITLE
zed-pcl in python

### ISSUE THREAD

**Issue by hannibal-paul** [stereolabs/zed-pcl#12]
I want to processes the point cloud obtained from zed-mini in real time using python.
Can you please provide us the implementation of zed-pcl in python?

Thanks in advance!

**Comment by xkevincode** [comment]
Have you succeed in processing point cloud data from Zed in Python, I also meet this difficulity. Thanks

**Comment by hannibal-paul** [comment]
Hi @xkevincode,
Try https://github.com/stereolabs/zed-python-api/tree/master/examples. It worked for me.
