### ISSUE TITLE
save point cloud data 

### ISSUE THREAD

**Issue by blueevangelion** [stereolabs/zed-pcl#2]
Is it a way to save the point cloud data from ZED?

**Comment by adujardin** [comment]
Hi,
Yes, have a look at this other [zed sample](https://github.com/stereolabs/zed-save-depth). Or if you want to save a PCL point cloud, you can also use [this](http://pointclouds.org/documentation/tutorials/writing_pcd.php)

**Comment by UserFLO** [comment]
Hi i'am trying to find a way to save my sl::MAt to pcl file. Do you have an idea ? 
Thanks
