### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by itskalvik** [stereolabs/zed-pcl#4]
Hello, I have the zed sdk on a Nvidia Jetson Tx1 along with pcl(1.8.0) and opencv(2.4.13) build from source. I didn't get any errors when I ran cmake and make,but when I run the program I get a segmentation fault.

**Comment by obraun-sl** [comment]
Hi,

Can you indicate the JetPack version you are using? 
Did you test the other samples provided by the ZED SDK installation to see if it is working?

Best,
/_OB_/

**Comment by itskalvik** [comment]
I had an issue with my pcl installation.
Thank you.
