### ISSUE TITLE
PCL ZED 3D Viewer shows static red - green - black

### ISSUE THREAD

**Issue by revilokeb** [stereolabs/zed-pcl#5]
**Issue:** PCL ZED 3D Viewer is only showing static red / green / black areas as shown on the screenshot

![zed_pcl](https://cloud.githubusercontent.com/assets/10588773/18293222/c9bc2656-7491-11e6-98ec-87cb3d34e379.png)

**Setup:** Ubuntu 14.04, PCL-1.7 installed from binaries, ZED SDK 1.1, Titan X (Maxwell) GPU

**Comments:**
- ZED camera is working without problems with zed-matlab, zed-ros-wrapper, zed-tracking-viewer, zed-opencv
- GPU (driver, cuda) is correctly installed

Any explanation how this is coming about and what could be done?

**Comment by obraun-sl** [comment]
Hi,

The image you see is the center of the axis that define the (0,0,0) of the point cloud. For some reason (with PCL1.7 from ubuntu package and PCL 1.8 built from sources), the point cloud is strongly "zoomed in" when sample is launched. We are going to investigate on that.

Just use the mouse wheel to zoom out and you should see the point cloud.

Best,
/_OB_/

**Comment by revilokeb** [comment]
@sl-braun many thanks!
