### ISSUE TITLE
Running zed-pcl on ubuntu 16.04 not finding opencv

### ISSUE THREAD

**Issue by ahsteven** [stereolabs/zed-pcl#6]
Hi I have been able to run the zed-opencv example on my ubuntu 16.04 system. However, when I try to build the zed-pcl example I get the error:

`CMake Warning at /home/teves/opencv/cmake/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

CMake Error at CMakeLists.txt:30 (find_package):
  Found package configuration file:

    /home/teves/opencv/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!`

I dont understand why one version is able to find the correct opencv and the other is not. Also not sure why it says found windows pack as I do not have a windows version of opencv in that directory. Please advise.

**Comment by santonatos** [comment]
what is your cmakeList file?
