### ISSUE TITLE
pcl input set not organized

### ISSUE THREAD

**Issue by santonatos** [stereolabs/zed-pcl#7]
I am using point clouds I captured with zed, but when I try to compute the normals with fast integral images method, I get the error:

[pcl::IntegralImageNormalEstimation::setInputCloud] Input dataset is not organized (height = 1).

Should something be tweaked in the while loop when we transfer the mat to the cloud?

**Comment by adujardin** [comment]
Hi,
The cloud dimension wasn't set. It should work now.

**Comment by santonatos** [comment]
thank you for the quick reply, I will test it and I will let you know.

**Comment by santonatos** [comment]
so even though it is organized now when its being captured, after I save it to a pcd file and I load it to another function it is not organized anymore. Any idea why that would happen?

**Comment by adujardin** [comment]
The point cloud is saved as a list in the pcd file and therefore lose its organization.

I don't use the point cloud recording that much so it may not be the best solution but I would save the point cloud as a CSV file or custom plain text format (keeping the line and column information).

**Comment by santonatos** [comment]
can I use the loadPCD and writeToPCD functions for text files too? or should I write my own functions for that? are there ready functions somewhere for txt file to point cloud?

**Comment by adujardin** [comment]
My bad, it turns out pcd format handles organized point cloud as well according to [this](http://pointclouds.org/documentation/tutorials/pcd_file_format.php).
You can save a point cloud like [this](http://pointclouds.org/documentation/tutorials/writing_pcd.php)

**Comment by santonatos** [comment]
My bad, in my save function I was setting the width to something and the  height to 1 manually because it did not have a height (before your commit). Now after your update  I can delete this line and I will retry. Thank you for your quick reply I will let you know.

**Comment by santonatos** [comment]
it works now, thank you, the code you added fixed it
